# Generated by Django 4.2.7 on 2023-12-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('universidad', models.CharField(max_length=100, verbose_name='Universidad')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
            ],
        ),
    ]
