# Generated by Django 4.2.7 on 2023-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
    ]
