# Generated by Django 4.2.7 on 2023-12-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento',
            field=models.CharField(max_length=100, null=True, verbose_name='Evento'),
        ),
    ]
