# Generated by Django 4.2.7 on 2023-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_evento_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electronico')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('telefono', models.IntegerField(max_length=10, verbose_name='Telefono')),
                ('celular', models.IntegerField(max_length=10, verbose_name='Celular')),
                ('institucion_recep', models.CharField(max_length=100, verbose_name='Institucion receptora')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('nomb_apell', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('cedula', models.IntegerField(max_length=10, verbose_name='Cedula')),
                ('tip_practica', models.CharField(max_length=20, verbose_name='Tipo de Practica')),
                ('campo_am', models.CharField(max_length=100, verbose_name='Campo Amplio')),
                ('campo_es', models.CharField(max_length=100, verbose_name='Campo especifico')),
                ('tutor_acad', models.CharField(max_length=100, verbose_name='Tutor academico')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
